### ISSUE TITLE
Prepare public status on Github

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-deploy#12]
### Assessment
- A complete rebase is required because real usernames and passwords were hardcoded at some point.
- Internal IPs might have been exposed

### TODO
- [x] Scan for security leaks
    - [x] passed: `truffleHog --regex --entropy=True https://github.com/satzbeleg/evidence-deploy.git` 
    - [x] passed, only param names and obvious toy strings: `gittyleaks -link https://github.com/satzbeleg/evidence-deploy`
    - [x] passed: `truffleHog --regex --entropy=True --since_commit=be65bab https://github.com/satzbeleg/evidence-deploy.git` 
- [x] Change Host IP/Port to other more generic examples
- [ ] Delete unnecessary comments and code
- [x] Translate comments/readme to EN
- [ ] Transfer the whole repo to a backup location (incl. issues)
- [ ] Create a new repo with a clean code version as initial upload
